# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip2app', '0003_regularuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularuser',
            name='age',
            field=models.IntegerField(),
        ),
    ]
