# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip2app', '0004_auto_20190306_2029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz',
            new_name='QuizObject',
        ),
    ]
