# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-22 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ip2app', '0006_quizobject_url_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip2app.QuizObject')),
            ],
        ),
        migrations.AddField(
            model_name='regularuser',
            name='firstName',
            field=models.CharField(default=django.utils.timezone.now, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regularuser',
            name='lastName',
            field=models.CharField(default=django.utils.timezone.now, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regularuser',
            name='userName',
            field=models.CharField(default=django.utils.timezone.now, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userquiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip2app.RegularUser'),
        ),
    ]
