# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-22 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip2app', '0007_auto_20190322_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizobject',
            old_name='url_slug',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='question',
            name='question_answer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
