# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip2app', '0010_remove_question_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_answer',
        ),
    ]
