# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ip2app', '0011_remove_question_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_answer',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='user_response',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
